cart/urls.py
from django.urls import path 
from . import views 

app_name = 'cart'

urlpatterns = [
    path('list/',views.cart_details,name='cart_details'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls',namespace='shop')),
    path('cart/',include('cart.urls', namespace='cart')),
    path('order/',include('order.urls', namespace='order')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path 
from . import views 

app_name = 'order'

urlpatterns = [
    path('create/',views.create_order, name='create_order'),
    path('invoice/<int:order_id>/pdf/',views.invoice,name='invoice')
    
]

shop/urls.py
from django.urls import path 
from . import views 

app_name='shop'

urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_details,name='product_details'),
    


]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models

from shop.models import Product 

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    post_code = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return f'Order {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity 

shop/models.py
from django.db import models
from django.urls import reverse 


class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args = [self.slug])

    def __str__(self):
        return self.name 


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits= 10, decimal_places=2)
    stock = models.PositiveBigIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        # index_together = (('id','slug'))
        indexes = [
            models.Index(fields=['id', 'slug']),
        ]

    def get_absolute_url(self):
        return reverse('shop:product_details', args = [self.id, self.slug])

    def __str__(self):
        return self.name 
    

cart/forms.py
from django import forms 

class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=10)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

order/forms.py
from django import forms 
from .models import Order 


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order 
        fields = ['first_name','last_name','email','address','city','post_code']
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'post_code':forms.TextInput(attrs={'class':'form-control'})
            
        }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST


from .cart import Cart
from shop.models import Product 
from .forms import CartAddForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)

    if form.is_valid():
        print('form is valid')
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
        return redirect('cart:cart_details')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_details')


def cart_details(request):
    print('method is called')
    cart = Cart(request)
    for item in cart:
        item['update_quantity'] = CartAddForm(initial={'quantity': item['quantity'],'update': True})
    return render(request,'cart/cart_details.html',{'cart':cart})

order/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Order, OrderItem 
from .forms import OrderForm
from cart.cart import Cart 


def create_order(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            print('order',form)
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
        
            cart.clear()
        
            return render(request,'order/order_done.html',{'order':order})
        else:
            print('form error ',form.errors)
        # return HttpResponse('something went wrong')
    else:
        form = OrderForm()
        return render(request,'order/create_order.html',{'form':form,'cart':cart})
    

from django.conf import settings 
from django.http import HttpResponse
from django.template.loader import render_to_string 
from weasyprint import HTML 
import weasyprint


def invoice(request,order_id):
    
    order = get_object_or_404(Order, id=order_id)
    html_string = render_to_string('order/pdf.html',{'order':order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f' filename=invoice_{order_id}.pdf'
    HTML(string=html_string).write_pdf(response)
    
    # html = render_to_string('order/pdf.html',{'order':order})

    # response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'filename= order_{order_id}.pdf'
    # weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS])

    return response 

shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddForm
from .models import Category, Product


def product_list(request, category_slug = None):
    category = None 
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    context = {
        'categories':categories,
        'products':products,
        'category':category
    }
    print(category)
    return render(request,'shop/product/list.html',context)

    
def product_details(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    form = CartAddForm()

    return render(request,'shop/product/details.html',{'product':product,'form':form})

cart/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog {% endblock %}</title>
    
    <!-- BOOTSTRAP  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>

    <!-- navbar  -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container ">
          <a class="navbar-brand" href="/">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav ">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>


    <div class="container">

        {% block content %}
        {% endblock %}
    </div>

    <!-- BOOTSTRAP  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

cart/templates/cart/cart_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %} My Cart {% endblock %}

{% block content %}

<div class="row">
    <div class="col-8 mx-auto">
        <h1>Your Shopping Cart</h1>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <div class="product-img" style="width: 100px; border: 1px solid;">

                            <a href="{{product.get_absolute_url}}">
                                {% if product.image %} <img src="{{product.image.url}}" class="img-fluid" alt="">
                                {% else %} <img src="{% static 'images/no-pic.jpg' %}" class="img-fluid" alt="">
                                {% endif %}
                            </a>
                        </div>
                    </td>
                    <td>{{product.name}}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {% csrf_token %}
                            {{item.update_quantity.quantity}}
                            {{item.update_quantity.update}}
                            <input type="submit" value="update">
                        </form>
                    </td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}">remove</a></td>
                    <td>{{item.price}}</td>
                    <td>{{item.total_price}}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr>
                    <td colspan="4"></td>
                    <td class="fw-bold">Total</td>
                    <td class="fw-bold">$ {{cart.get_total_price}}</td>
                </tr>
            </tbody>
        </table>

        <p class="text-end">
            <a href="{% url 'shop:product_list' %}" class="btn btn-secondary">Continue Shopping</a>
            <a href="{% url 'order:create_order' %}" class="btn btn-primary">Checkout</a>
        </p>

    </div>
</div>

{% endblock %}

order/templates/order/create_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Order Now {% endblock %}

{% block content %}

<div class="row d-flex justify-content-evenly">
    <div class="col-6 bg-secondary p-3 " >
        <h3>Checkout</h3>
        <form action="" method="post">
            {% csrf_token %}
           <!-- {% for i in form %}
            <label for="" class="text-white">{{i.label}}</label>
            <input type="{{i.type}}" class="form-control" placeholder="{{i.label}}"> -->
           <!-- {% endfor %} -->
            <!-- {{form.as_p}} -->
             {% for f in form %}
             <label for="">{{f.label}}</label>
             {{f}}
             {% endfor %}
            <input type="submit" value="Confirm Order" class="mt-2 btn btn-primary float-end">
        </form>
    </div>

    <div class="col-3 ">
        <div class="row bg-secondary p-3">
            <h4 class="ps-0">Your Order:</h4>
           <table class="table table-bordered">
               {% for item in cart %}
            <tr>
                <td>{{item.quantity}}x</td>
                <td>{{item.product.name}}</td>
                <td>{{item.total_price}}</td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td>${{cart.get_total_price}}</td>
            </tr>
           </table>
        </div>
    </div>
</div>


{% endblock %}

order/templates/order/order_done.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Thank you! {% endblock %}

{% block content %}

<div class="text-center">
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is 
  <strong>{{ order.id }}</strong>.</p>
 <br>
  <a href="{% url 'shop:product_list' %}" class="btn btn-secondary">Continue Shopping</a>
</div>

{% endblock %}

order/templates/order/pdf.html
<html lang="en">
<body>
    
    <h1>My Shop</h1>

    <p>
        Invoice no. {{order.id}} <br>
        <span>{{order.created}}</span>
    </p>

    <h3>Bill to</h3>
    <p>
        {{order.first_name}} {{order.last_name}} <br>
        {{order.email}} <br>
        {{order.address}} <br>
        {{order.post_code}}, {{order.city}}
    </p>

    <h3>Items bought</h3>

    <table>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Cost</th>
        </tr>
        {% for item in order.items.all %}
        <tr>
            <td>{{item.product.name}}</td>
            <td>{{item.price}}</td>
            <td>{{item.quantity}}</td>
            <td>{{item.get_cost}}</td>
        </tr>
        {% endfor %}
        <tr>
            <td value="colspan=3">Total</td>
            <td>${{order.get_total_cost}}</td>
        </tr>
    </table>

    <hr>
    <p>
        {% if order.paid %} Paid {% else %} Updaid {% endif %}
    </p>

</body>
</html>

shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog {% endblock %}</title>
    
    <!-- BOOTSTRAP  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- font awesome  -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>

    <!-- navbar  -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container ">
          <a class="navbar-brand" href="/">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav ">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown link
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="btn btn-primary" href="{% url 'cart:cart_details' %}"><i class="bi bi-cart-check-fill"></i> &nbsp;{{cart|length}}</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


    <div class="container">

        {% block content %}
        {% endblock %}
    </div>

    <!-- BOOTSTRAP  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/product/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {% if product.category %} {{product.category.name}} {% else %} Products {% endif %}
{% endblock %}

{% block content %}

<div class="row mx-auto">
    <div class="col-4">
        {% if product.image %}
        <img src="{{ product.image.url}}" class="img-fluid" alt="">
        {% else %}
        <img src="{% static 'images/no-pic.jpg' %}" class="img-fluid" alt="">
        {% endif %}
    </div>
    <div class="col-8">
        <h1>{{product.name}}</h1>
        <b><a href="{{product.category.get_absolute_url}}">{{product.category.name}}</a></b>
        <!-- <hr> -->
        <hr>
        <p>
            {{product.description|linebreaks}}
        </p>
        <hr>
        <h3>$ {{product.price}}</h3>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Add Cart">
        </form>
    </div>
</div>

{% endblock %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if category %} {{category.name}} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-4">
        <h3>Categories</h3>
        <ul class="list-group">
            <li {% if not category %} class="bg-dark list-group-item" {% endif %} class="list-group-item">
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %} class = 'bg-dark list-group-item ' {% endif %}  class="list-group-item">
                <a href="{{ c.get_absolute_url }}">{{c.name}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <!-- main  -->
     <div class="col-8">
        <h3>{% if category %}{{category.name}} {% else %}Products {% endif %}</h3>
        <div class="row">
            {% for product in products %}
            <div class="col-4">
                <div class="card">
                    <a href="{{ product.get_absolute_url }}">
                        <div class="card-img">
                            {% if product.image %} <img src="{{product.image.url}}" class="img-fluid" alt=""> {% else %} <img src="{% static '/images/no-pic.jpg' %}" class="img-fluid" alt=""> {% endif %}
                        </div>

                        <div class="fw-bold text-center p-3 pb-0">{{product.name}}</div>
                    </a>
                    <hr>
                    <div class="card-body text-center mt-0 pt-0">
                        <div class="card-subtitle fw-bold">$ &nbsp;{{product.price}}</div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
     </div>
</div>
{% endblock %}